"""
agent/state.py

Defines the shared state object that flows through every node
in the LangGraph agent.

Think of this as the 'notepad' that gets passed between nodes —
each node reads what it needs and writes its outputs back to it.
"""

from typing import Any

from langchain_core.documents import Document

# TypedDict lets us define a dictionary with specific keys and types.
# It's like a regular Python dict but with a declared schema —
# every key is named and its value type is specified.
# This gives us autocomplete in VS Code and catches type errors early.
from typing_extensions import TypedDict


class AgentState(TypedDict):
    """
    The complete state of the agent at any point in its execution.

    Every node in the graph receives this state as input and returns
    a (partial) updated version of it as output. LangGraph automatically
    merges the updates back into the full state.

    Fields are added progressively as the agent moves through nodes:
    - question:       set at the start, never changes
    - route:          set by the Router node
    - retrieved_docs: set by the Retriever node
    - context:        set by the Retriever node (formatted string)
    - answer:         set by the Analyst node
    - confidence:     set by the Evaluator node
    - retry_count:    tracks how many times we've retried
    - final_answer:   the answer approved by the Evaluator
    """

    # The user's original question — set once at the start, read by all nodes
    question: str

    # The route decision made by the Router node.
    # One of: "retrieval", "comparison", "summary"
    # This is what the edge conditions read to decide which node runs next.
    route: str

    # The raw Document objects retrieved from ChromaDB.
    # Kept so the UI can display source citations.
    retrieved_docs: list[Document]

    # The formatted context string injected into the LLM prompt.
    # This is the text version of retrieved_docs, ready for the prompt template.
    context: str

    # The answer generated by the Analyst node.
    answer: str

    # A confidence score (0.0 to 1.0) assigned by the Evaluator node.
    # Below a threshold, the agent retries the Analyst node.
    confidence: float

    # Counts how many times we've retried to prevent infinite loops.
    # We cap retries at 1 — if the second attempt is also low confidence,
    # we return it anyway with a warning.
    retry_count: int

    # The final approved answer that gets returned to the user.
    # Set by the Evaluator once confidence is acceptable.
    final_answer: str

    # Any extra metadata we want to pass through — which node was used,
    # timing information, etc. Displayed in the Streamlit UI for demo purposes.
    metadata: dict[str, Any]
